### ISSUE TITLE
Wallaby for UI Tests?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-todo-list-tutorial#25]
We used Wallaby on a previous client (Elixir/Phoenix) project and it was OK... 
We stopped using it because our use-case didn't justify the extra overhead.

But on a recent project it was proposed as the testing tool.
So I'm considering revisiting it.

Not impressed by the fact that, at the time of writing it has "CI Failing" and only **42%** coverage ... 
https://github.com/elixir-wallaby/wallaby
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/194400/159513130-7195db5c-d7c3-47ba-b91f-a6b0a8b1d3bb.png">

Seems like a _testing_ tool of all things could get coverage up to **100%** the way we do for ***all*** our projects. 💭 
But on the basis that enough people are using it ... we can hopefully _assume_ that it's reliable. 

# Todo

+ [ ] Explore using Wallaby for a basic todo list test 
+ [ ] Determine if the experience is smooth or tedious
+ [ ] Use it to build one more feature for this tutorial: editing a todo list item.
+ [ ] Decide if it's worth pursuing in other UI-heavy projects.

**Comment by nelsonic** [comment]
Relevant reading: https://www.wyeworks.com/blog/2022/04/21/adding-e2e-tests-to-an-elixir-library/
